//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abuse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abuse()
        {
            this.AbuseRatings = new HashSet<AbuseRating>();
            this.AbuseSpaces = new HashSet<AbuseSpace>();
            this.AbuseTypes = new HashSet<AbuseType>();
        }
    
        public System.Guid Id { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTimeOffset> ReportedAt { get; set; }
        public System.Guid ReporterId { get; set; }
        public string FileName { get; set; }
    
        public virtual User Reporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbuseRating> AbuseRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbuseSpace> AbuseSpaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbuseType> AbuseTypes { get; set; }
    }
}
