//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbuseType
    {
        public System.Guid Id { get; set; }
        public System.Guid AbuseId { get; set; }
        public System.Guid TypeId { get; set; }
    
        public virtual Abuse Abuse { get; set; }
        public virtual AbuseTypeDictionary AbuseTypeDictionary { get; set; }
    }
}
