//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.Messages = new HashSet<Message>();
            this.ChatMembers = new HashSet<ChatMember>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid SpaceId { get; set; }
        public Nullable<System.Guid> ApprovedMessageOfferHistoryId { get; set; }
        public Nullable<System.Guid> LastMessageOfferId { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMember> ChatMembers { get; set; }
        public virtual Space Space { get; set; }
        public virtual MessageOfferHistory ApprovedMessageOfferHistory { get; set; }
        public virtual MessageOffer LastMessageOffer { get; set; }
    }
}
