//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterRootDictionary
    {
        public System.Guid Id { get; set; }
        public System.Guid FilterId { get; set; }
        public System.Guid RootDictionaryId { get; set; }
    
        public virtual RootDictionary RootDictionary { get; set; }
        public virtual Filter Filter { get; set; }
    }
}
