//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filter()
        {
            this.FilterRootDictionaries = new HashSet<FilterRootDictionary>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Data.Entity.Spatial.DbGeography BoundingBox { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public System.DateTimeOffset RentStartDate { get; set; }
        public bool CheckSizeType { get; set; }
        public bool CheckType { get; set; }
        public bool CheckAccessType { get; set; }
        public string Location { get; set; }
        public Nullable<System.Guid> ZipCodeId { get; set; }
        public double TopLatitude { get; set; }
        public double BottomLatitude { get; set; }
        public double LeftLongitude { get; set; }
        public double RightLongitude { get; set; }
    
        public virtual User User { get; set; }
        public virtual Zip Zip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilterRootDictionary> FilterRootDictionaries { get; set; }
    }
}
