//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> ProcessedDate { get; set; }
        public decimal Amount { get; set; }
        public System.Guid SpaceId { get; set; }
        public System.Guid SenderId { get; set; }
        public string RecepientToken { get; set; }
        public string SenderToken { get; set; }
    
        public virtual User User { get; set; }
        public virtual Space Space { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
