//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageOfferHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageOfferHistory()
        {
            this.MessageOffers = new HashSet<MessageOffer>();
            this.Chats = new HashSet<Chat>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MessageOfferId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid StatusId { get; set; }
        public System.DateTimeOffset ChangedStatusDate { get; set; }
    
        public virtual MessageOffer MessageOffer { get; set; }
        public virtual MessageOfferStatus MessageOfferStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageOffer> MessageOffers { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
    }
}
