//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public System.DateTimeOffset ReceivedDate { get; set; }
        public System.DateTimeOffset SentDate { get; set; }
        public string MessageText { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ChatId { get; set; }
        public System.Guid DeliveredStatusId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Chat Chat { get; set; }
        public virtual MessageDeliveredStatus MessageDeliveredStatu { get; set; }
        public virtual MessageOffer MessageOffer { get; set; }
    }
}
