//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageOffer()
        {
            this.MessageOfferHistories = new HashSet<MessageOfferHistory>();
            this.Chats = new HashSet<Chat>();
        }
    
        public System.Guid Id { get; set; }
        public decimal Rate { get; set; }
        public System.Guid RentPeriodId { get; set; }
        public Nullable<System.Guid> CurrentMessageOfferHistory { get; set; }
        public Nullable<System.DateTimeOffset> StopAt { get; set; }
        public System.DateTimeOffset RentSince { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual RentPeriodType RentPeriodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageOfferHistory> MessageOfferHistories { get; set; }
        public virtual MessageOfferHistory MessageOfferHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
    }
}
