//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rating()
        {
            this.AbuseRatings = new HashSet<AbuseRating>();
        }
    
        public System.Guid Id { get; set; }
        public int Rank { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SpaceOwnerReply { get; set; }
        public Nullable<System.DateTimeOffset> RepliedAt { get; set; }
    
        public virtual MessageOfferHistory MessageOfferHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbuseRating> AbuseRatings { get; set; }
    }
}
