//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public System.Guid Id { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> SentDate { get; set; }
        public string StripeTransactionId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
