//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RootDictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RootDictionary()
        {
            this.FilterRootDictionaries = new HashSet<FilterRootDictionary>();
        }
    
        public System.Guid Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilterRootDictionary> FilterRootDictionaries { get; set; }
        public virtual SizeType SizeType { get; set; }
        public virtual SpaceAccessType SpaceAccessType { get; set; }
        public virtual SpaceType SpaceType { get; set; }
    }
}
