//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceBusy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaceBusy()
        {
            this.PrevSpaceBusy = new HashSet<SpaceBusy>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SpaceId { get; set; }
        public Nullable<System.Guid> NextSpaceBusyID { get; set; }
        public System.DateTimeOffset StartDate { get; set; }
        public Nullable<System.DateTimeOffset> EndDate { get; set; }
    
        public virtual Space Space { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpaceBusy> PrevSpaceBusy { get; set; }
        public virtual SpaceBusy NextSpaceBusy { get; set; }
    }
}
