//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSet
    {
        public System.Guid Id { get; set; }
        public int Size { get; set; }
        public System.Guid ZipId { get; set; }
        public int Type { get; set; }
        public int Accessebility { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Zip Zip { get; set; }
    }
}
