//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string PushNotificationToken { get; set; }
        public string MobileEndpoint { get; set; }
        public string SubscriptionEndpoint { get; set; }
        public string TopicEndpoint { get; set; }
        public bool IsPushNotificationEnabled { get; set; }
    
        public virtual User User { get; set; }
    }
}
