//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Messages = new HashSet<Message>();
            this.Spaces = new HashSet<Space>();
            this.UserDevices = new HashSet<UserDevice>();
            this.Chats = new HashSet<Chat>();
            this.ChatMembers = new HashSet<ChatMember>();
            this.MessageOfferHistories = new HashSet<MessageOfferHistory>();
            this.RefreshTokens = new HashSet<RefreshToken>();
            this.PaymentPoints = new HashSet<PaymentPoint>();
            this.Abuses = new HashSet<Abuse>();
            this.Filters = new HashSet<Filter>();
        }
    
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string PaymentSystemSecret { get; set; }
        public Nullable<decimal> AvgRate { get; set; }
        public System.Guid PhoneVerificationStatusID { get; set; }
        public string AvatarLink { get; set; }
        public string Password { get; set; }
        public int CountRating { get; set; }
        public string FacebookID { get; set; }
        public System.Guid EmailVerificationStatusID { get; set; }
        public bool IsExternal { get; set; }
        public Nullable<System.Guid> OutPaymentPointId { get; set; }
        public Nullable<System.Guid> IncPaymentPointId { get; set; }
        public int AccessFailedCount { get; set; }
        public Nullable<System.DateTimeOffset> LockoutEndDate { get; set; }
        public string StripeCustomerId { get; set; }
        public int TotalUnreadMessages { get; set; }
        public string StripeAccountId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Space> Spaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDevice> UserDevices { get; set; }
        public virtual PhoneVerificationStatus PhoneVerificationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMember> ChatMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageOfferHistory> MessageOfferHistories { get; set; }
        public virtual EmailVerificationStatus EmailVerificationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefreshToken> RefreshTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentPoint> PaymentPoints { get; set; }
        public virtual PaymentPoint IncPaymentPoint { get; set; }
        public virtual PaymentPoint OutPaymentPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abuse> Abuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filter> Filters { get; set; }
    }
}
