//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weezlabs.Storgage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weezlabs.Storgage.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abuse with Id = {0} does not exist..
        /// </summary>
        public static string AbuseDoesntExist {
            get {
                return ResourceManager.GetString("AbuseDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot post an abuse without any abuse reasons in &apos;AbuseType&apos; array..
        /// </summary>
        public static string AbuseTypeRequired {
            get {
                return ResourceManager.GetString("AbuseTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abuse type can not be duplicated for single abuse..
        /// </summary>
        public static string AbuseTypeUnique {
            get {
                return ResourceManager.GetString("AbuseTypeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for current resource..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception with Amazon service..
        /// </summary>
        public static string AmazonException {
            get {
                return ResourceManager.GetString("AmazonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is succcess..
        /// </summary>
        public static string AuthSuccess {
            get {
                return ResourceManager.GetString("AuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lease cannot start in past..
        /// </summary>
        public static string BadFilterRentStartDate {
            get {
                return ResourceManager.GetString("BadFilterRentStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer rent date cannot start earlier than now or be later that the end date..
        /// </summary>
        public static string BadRentSinceDate {
            get {
                return ResourceManager.GetString("BadRentSinceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already have bank account. We can&apos;t create new before deleting exists..
        /// </summary>
        public static string BankAccountAlreadyExists {
            get {
                return ResourceManager.GetString("BankAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have bank account yet..
        /// </summary>
        public static string BankAccountNotFound {
            get {
                return ResourceManager.GetString("BankAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geographic area you have specified is too large. Please set more specific area..
        /// </summary>
        public static string BoundingBoxAreaExceedsLimit {
            get {
                return ResourceManager.GetString("BoundingBoxAreaExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geographic coordinates do not represent a surface..
        /// </summary>
        public static string BoundingBoxMustBeSurface {
            get {
                return ResourceManager.GetString("BoundingBoxMustBeSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot approve or reject non pending offer..
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with identifier &quot;{0}&quot; not found. Maybe card was removed..
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You alwas have chat this owner..
        /// </summary>
        public static string ChatAlwaysExist {
            get {
                return ResourceManager.GetString("ChatAlwaysExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat has offer with rejected status. You cannot post messages or another offers to this chat..
        /// </summary>
        public static string ChatClosedForNewMessage {
            get {
                return ResourceManager.GetString("ChatClosedForNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat has approved or stopped offer. You cannot post another offers, but you can post messages..
        /// </summary>
        public static string ChatClosedForNewOffer {
            get {
                return ResourceManager.GetString("ChatClosedForNewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with identifier {0} has not begun a chat with a host of space with identifier {1}..
        /// </summary>
        public static string ChatNotExistForSpace {
            get {
                return ResourceManager.GetString("ChatNotExistForSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with identifier {0} not found. Maybe chat was removed..
        /// </summary>
        public static string ChatNotFound {
            get {
                return ResourceManager.GetString("ChatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Storgage] Confirm email..
        /// </summary>
        public static string ConfirmEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the mobile endpoint creating. Status code: {0}..
        /// </summary>
        public static string CreateMobileEndpointError {
            get {
                return ResourceManager.GetString("CreateMobileEndpointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error during the mobile endpoint creating. See log to get detail exception..
        /// </summary>
        public static string CreateMobileEndpointException {
            get {
                return ResourceManager.GetString("CreateMobileEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the topic error creating. Status code: {0}..
        /// </summary>
        public static string CreateTopicError {
            get {
                return ResourceManager.GetString("CreateTopicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have debit card yet..
        /// </summary>
        public static string DebitCardNotFound {
            get {
                return ResourceManager.GetString("DebitCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems occurred when deleting file from Amazon S3 bucket. But rows from database removed..
        /// </summary>
        public static string DeleteFileError {
            get {
                return ResourceManager.GetString("DeleteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device token {0} always exist..
        /// </summary>
        public static string DeviceTokenAlwaysExist {
            get {
                return ResourceManager.GetString("DeviceTokenAlwaysExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device token cannot be empty..
        /// </summary>
        public static string DeviceTokenEmpty {
            get {
                return ResourceManager.GetString("DeviceTokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device token {0} not found..
        /// </summary>
        public static string DeviceTokenNotFound {
            get {
                return ResourceManager.GetString("DeviceTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates are not allowed in the {0} collection..
        /// </summary>
        public static string DuplicatesNotAllowed {
            get {
                return ResourceManager.GetString("DuplicatesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string EmailConfirmSuccess {
            get {
                return ResourceManager.GetString("EmailConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West and East longitudes shouldn&apos;t be equals..
        /// </summary>
        public static string EqualLongitudes {
            get {
                return ResourceManager.GetString("EqualLongitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External user can not set password..
        /// </summary>
        public static string ExternalUserCanNotSetPassword {
            get {
                return ResourceManager.GetString("ExternalUserCanNotSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook token is incorrect..
        /// </summary>
        public static string FacebookTokenError {
            get {
                return ResourceManager.GetString("FacebookTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; exists..
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter with identifier {0} not found. Maybe the filter was removed..
        /// </summary>
        public static string FilterNotFound {
            get {
                return ResourceManager.GetString("FilterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get endpoint attributes operation is failed with status {0}..
        /// </summary>
        public static string GetEndpointAttributesError {
            get {
                return ResourceManager.GetString("GetEndpointAttributesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception during the get endpoint attributes. See log to get detailed information..
        /// </summary>
        public static string GetEndpointAttributesException {
            get {
                return ResourceManager.GetString("GetEndpointAttributesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request parameter should not be empty..
        /// </summary>
        public static string IncomingParameterRequired {
            get {
                return ResourceManager.GetString("IncomingParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal user must have email and phone. External users (facebook user) may don&apos;t have them..
        /// </summary>
        public static string InternalUserMustHaveEmailAndPhone {
            get {
                return ResourceManager.GetString("InternalUserMustHaveEmailAndPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should upload just one photo for avatar, but trying to upload {0}..
        /// </summary>
        public static string InvalidAvatarUpload {
            get {
                return ResourceManager.GetString("InvalidAvatarUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance shouldn&apos;t be negative..
        /// </summary>
        public static string InvalidDistance {
            get {
                return ResourceManager.GetString("InvalidDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email &apos;{0}&apos; format..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude {0} is invalid value. Latitude should be between {1} and {2}..
        /// </summary>
        public static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North latitude should be higher than south..
        /// </summary>
        public static string InvalidLatitudeDifference {
            get {
                return ResourceManager.GetString("InvalidLatitudeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit value shouldn&apos;t be negative..
        /// </summary>
        public static string InvalidLimit {
            get {
                return ResourceManager.GetString("InvalidLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should send request with not empty list of photo for delete..
        /// </summary>
        public static string InvalidListOfPhotoForDelete {
            get {
                return ResourceManager.GetString("InvalidListOfPhotoForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude {0} is invalid value. Longitude should be between {1} and {2}..
        /// </summary>
        public static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset value shouldn&apos;t be negative..
        /// </summary>
        public static string InvalidOffset {
            get {
                return ResourceManager.GetString("InvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string InvalidPasswordConfirmation {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price format, only two digits after point..
        /// </summary>
        public static string InvalidPriceFormat {
            get {
                return ResourceManager.GetString("InvalidPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value &quot;{0}&quot; of parameter &quot;{1}&quot; to type &quot;{2}&quot; for action &quot;{3}&quot;;.
        /// </summary>
        public static string InvalidQueryParameterType {
            get {
                return ResourceManager.GetString("InvalidQueryParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; doesn&apos;t have refresh token &quot;{1}&quot;..
        /// </summary>
        public static string InvalidRefreshTokenUser {
            get {
                return ResourceManager.GetString("InvalidRefreshTokenUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxRate value shouldn&apos;t be negative..
        /// </summary>
        public static string InvalidSpaceMaxRate {
            get {
                return ResourceManager.GetString("InvalidSpaceMaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinRate value shouldn&apos;t be negative..
        /// </summary>
        public static string InvalidSpaceMinRate {
            get {
                return ResourceManager.GetString("InvalidSpaceMinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxRate value should be higher than minRate..
        /// </summary>
        public static string InvalidSpaceRateRange {
            get {
                return ResourceManager.GetString("InvalidSpaceRateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string InvalidUserCredentials {
            get {
                return ResourceManager.GetString("InvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip shouldn&apos;t be empty or zip code with value {0} not found.
        /// </summary>
        public static string InvalidZip {
            get {
                return ResourceManager.GetString("InvalidZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of location should not exceed {0} characters..
        /// </summary>
        public static string LocationTooLong {
            get {
                return ResourceManager.GetString("LocationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed images length is {0} bytes. Trying to upload {1} bytes..
        /// </summary>
        public static string MaximumImageLength {
            get {
                return ResourceManager.GetString("MaximumImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed images count is {0}. Uploaded {1}. Trying to upload {2}..
        /// </summary>
        public static string MaximumPhotoForStorage {
            get {
                return ResourceManager.GetString("MaximumPhotoForStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with identifier {0} not found. Maybe message was removed..
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find parameter &apos;{0}&apos; in action &apos;{1}&apos;;.
        /// </summary>
        public static string MissedQueryParameter {
            get {
                return ResourceManager.GetString("MissedQueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} started new chat with you..
        /// </summary>
        public static string NewChatStartedNotification {
            get {
                return ResourceManager.GetString("NewChatStartedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new message from {0} {1}..
        /// </summary>
        public static string NewMessagesNotification {
            get {
                return ResourceManager.GetString("NewMessagesNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new offer from {0} {1}..
        /// </summary>
        public static string NewOfferNotification {
            get {
                return ResourceManager.GetString("NewOfferNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer with identifier {0} not found..
        /// </summary>
        public static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent start date can only be changed for offer in pending state.
        /// </summary>
        public static string OfferPendingStatusRequired {
            get {
                return ResourceManager.GetString("OfferPendingStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was approved by {0} {1}..
        /// </summary>
        public static string OfferWasApprovedNotification {
            get {
                return ResourceManager.GetString("OfferWasApprovedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer was expired..
        /// </summary>
        public static string OfferWasExpiredNotification {
            get {
                return ResourceManager.GetString("OfferWasExpiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer was rejected by {0} {1}..
        /// </summary>
        public static string OfferWasRejectedNotification {
            get {
                return ResourceManager.GetString("OfferWasRejectedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer was stopped by {0} {1}..
        /// </summary>
        public static string OfferWasStoppedNotification {
            get {
                return ResourceManager.GetString("OfferWasStoppedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone verification code is incorrect..
        /// </summary>
        public static string PhoneVerificationCodeInvalid {
            get {
                return ResourceManager.GetString("PhoneVerificationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post body request is empty or cannot be deserialized. Please see model schema..
        /// </summary>
        public static string PostBodyCannotBeNull {
            get {
                return ResourceManager.GetString("PostBodyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can post only message or offer..
        /// </summary>
        public static string PostMessagesBadFormat {
            get {
                return ResourceManager.GetString("PostMessagesBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rate user offer if it does not have status &apos;Stopped&apos;..
        /// </summary>
        public static string RateOfferError {
            get {
                return ResourceManager.GetString("RateOfferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating with Id = {0} does not exist..
        /// </summary>
        public static string RatingDoesntExist {
            get {
                return ResourceManager.GetString("RatingDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating with identifier not found..
        /// </summary>
        public static string RatingNotFound {
            get {
                return ResourceManager.GetString("RatingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You posted rating for this offer early..
        /// </summary>
        public static string RatingWasPostedAlways {
            get {
                return ResourceManager.GetString("RatingWasPostedAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token with identifier &quot;{0}&quot; not found. .
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} spaces match your search conditions. Check them!.
        /// </summary>
        public static string RelevantSpacesNotification {
            get {
                return ResourceManager.GetString("RelevantSpacesNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the mobile endpoint removing. Status code: {0}..
        /// </summary>
        public static string RemoveMobileEndpointError {
            get {
                return ResourceManager.GetString("RemoveMobileEndpointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error during the mobile endpoint removing. See log to get detail exception..
        /// </summary>
        public static string RemoveMobileEnpointException {
            get {
                return ResourceManager.GetString("RemoveMobileEnpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the topic removing. Status code: {0}..
        /// </summary>
        public static string RemoveTopicError {
            get {
                return ResourceManager.GetString("RemoveTopicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply on rating cannot be null or empty..
        /// </summary>
        public static string ReplyOnRatingEmptyError {
            get {
                return ResourceManager.GetString("ReplyOnRatingEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Storgage] Reset Password..
        /// </summary>
        public static string ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the message sending. Status code: {0}.
        /// </summary>
        public static string SendMessageError {
            get {
                return ResourceManager.GetString("SendMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error durring the message sending. See log to get detail exception..
        /// </summary>
        public static string SendMessageException {
            get {
                return ResourceManager.GetString("SendMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error durring the message serializing. See log to get detail exception..
        /// </summary>
        public static string SerializerMessageException {
            get {
                return ResourceManager.GetString("SerializerMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can and must upload single file only..
        /// </summary>
        public static string SingleFileMustBeAttached {
            get {
                return ResourceManager.GetString("SingleFileMustBeAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STORGAGE] Your security code is: {0}.
        /// </summary>
        public static string SmsVerificationMessage {
            get {
                return ResourceManager.GetString("SmsVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space with Id = {0} does not exist..
        /// </summary>
        public static string SpaceDoesntExist {
            get {
                return ResourceManager.GetString("SpaceDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space with identifier {0} is not listed or was deleted. .
        /// </summary>
        public static string SpaceIsNotActiveOrDeleted {
            get {
                return ResourceManager.GetString("SpaceIsNotActiveOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not change IsListed from false to true when IsOccupied is true.
        /// </summary>
        public static string SpaceIsOccupied {
            get {
                return ResourceManager.GetString("SpaceIsOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space with identifier {0} not found. Maybe space was removed..
        /// </summary>
        public static string SpaceNotFound {
            get {
                return ResourceManager.GetString("SpaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot stop status. You can stop only approved status..
        /// </summary>
        public static string StopStatusError {
            get {
                return ResourceManager.GetString("StopStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account was rejected. Reason: {0}..
        /// </summary>
        public static string StripeDisabledAccount {
            get {
                return ResourceManager.GetString("StripeDisabledAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error durring the mobile endpoint subscription. Status code: {0}..
        /// </summary>
        public static string SubscribeMobileEndpointError {
            get {
                return ResourceManager.GetString("SubscribeMobileEndpointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address must be unique. Maybe another user already uses this email..
        /// </summary>
        public static string UniqueEmailError {
            get {
                return ResourceManager.GetString("UniqueEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Id must be unique. Maybe another user already uses this Facebook Id..
        /// </summary>
        public static string UniqueFacebookIdError {
            get {
                return ResourceManager.GetString("UniqueFacebookIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the mobile endpoint unsubscription. Status code: {0}..
        /// </summary>
        public static string UnsubscribeMobileEndointError {
            get {
                return ResourceManager.GetString("UnsubscribeMobileEndointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type..
        /// </summary>
        public static string UnsupportedMediaType {
            get {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems occurred when uploading file to Amazon S3 bucket..
        /// </summary>
        public static string UploadFileError {
            get {
                return ResourceManager.GetString("UploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have access to this chat..
        /// </summary>
        public static string UserDesntHaveAccessToThisChat {
            get {
                return ResourceManager.GetString("UserDesntHaveAccessToThisChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email was confirmed earlier..
        /// </summary>
        public static string UserEmailActuallyConfirmed {
            get {
                return ResourceManager.GetString("UserEmailActuallyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email doesn&apos;t confirmed. You should confirm it before using forgot password method..
        /// </summary>
        public static string UserEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have Email. Set email and try again..
        /// </summary>
        public static string UserHaveNoEmail {
            get {
                return ResourceManager.GetString("UserHaveNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have phone. Set phone number and try again..
        /// </summary>
        public static string UserHaveNoPhone {
            get {
                return ResourceManager.GetString("UserHaveNoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect. Attempt {0}. Max amount of attempt is {1}.
        /// </summary>
        public static string UserIncorrectPassword {
            get {
                return ResourceManager.GetString("UserIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked till {0}..
        /// </summary>
        public static string UserIsBlockedTill {
            get {
                return ResourceManager.GetString("UserIsBlockedTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with identifier {0} not found. Maybe user was removed..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email {0} not found. Check email and try again..
        /// </summary>
        public static string UserNotFoundByEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User phone was confirmed earlier..
        /// </summary>
        public static string UserPhoneActuallyConfirmed {
            get {
                return ResourceManager.GetString("UserPhoneActuallyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of zip code should not exceed {0} characters..
        /// </summary>
        public static string ZipCodeTooLong {
            get {
                return ResourceManager.GetString("ZipCodeTooLong", resourceCulture);
            }
        }
    }
}
