DELETE FROM FilterRootDictionary
DELETE FROM Filter
GO

ALTER TABLE Filter ALTER COLUMN MinPrice MONEY NULL
ALTER TABLE Filter ALTER COLUMN MaxPrice MONEY NULL
ALTER TABLE Filter ADD CheckSizeType BIT NOT NULL
ALTER TABLE Filter ADD CheckType BIT NOT NULL
ALTER TABLE Filter ADD CheckAccessType BIT NOT NULL
GO